### ISSUE TITLE
Missing clip_embed file and clarification on sunrgbd_coda data root

### ISSUE THREAD

**Issue by rasd3** [zhenyuw16/Uni3DETR#10]
I am trying to reproduce the results of OV-Uni3DETR but encountered an issue with the zeroshot_path(clip text embedding) file. 

Specifically, the file referenced in zeroshot_path="clip_embed/sunrgbd_clip_a+cname_rn50_manyprompt_46c_coda.npy" is missing from the repository. I was unable to locate this .npy file in the provided code or any related documentation. Could you please provide guidance on where to find this file or how it can be generated?

Additionally, the data root for OV configuration is set to data/sunrgbd_coda. Could you clarify what "sunrgbd_coda" refers to and whether there are any specific instructions for setting it up? Any help on the proper dataset configuration or preprocessing steps would be greatly appreciated.

thank you

**Comment by rasd3** [comment]
Is the file clip_embed/sunrgbd_clip_a+cname_rn50_manyprompt_46c_coda.npy generated from the notebook in this repository: https://github.com/yangcaoai/CoDA_NeurIPS2023/blob/main/CLIP/notebooks/Prompt_Engineering_for_ImageNet.ipynb?

**Comment by rasd3** [comment]
I confirmed that the 'sunrgbd_clip_a+cname_rn50_manyprompt_46c_coda.npy' file can be created using the previous comment link, and I successfully reproduced the point-only performance during the experiment(9.11/48.4/18.25)

**Comment by rasd3** [comment]
I confirmed that the 'sunrgbd_clip_a+cname_rn50_manyprompt_46c_coda.npy' file can be created using the previous comment link, and I successfully reproduced the point-only performance during the experiment(9.11/48.4/18.25)

**Comment by Monet237** [comment]
Can you tell me the details？I'm having the same problem now. Thank you so much!

**Comment by happy91512** [comment]
I just generated the `clip_embed/sunrgbd_clip_a+cname_rn50_manyprompt_46c_coda.npy` file using this simple script, and the training has successfully started. I'll need to wait for the training results to determine whether everything is working correctly.

```
import numpy as np
import clip
import torch

# SUNRGBD 46-class names
class_names = ('chair', 'table', 'pillow', 'sofa_chair', 'desk', 'bed', 'sofa', 'computer', 'box',
               'lamp', 'garbage_bin', 'cabinet', 'shelf', 'drawer', 'sink', 'night_stand', 'kitchen_counter',
               'paper', 'end_table', 'kitchen_cabinet', 'picture', 'book', 'stool', 'coffee_table', 'bookshelf',
               'painting', 'key_board', 'dresser', 'tv', 'whiteboard', 'cpu', 'toilet', 'file_cabinet', 'bench',
               'ottoman', 'plant', 'monitor', 'printer', 'recycle_bin', 'door', 'fridge', 'towel', 'cup', 'mirror',
               'laptop', 'cloth')

# Prompt templates
templates = [
    "a photo of a {}.",
    "a rendering of a {}.",
    "a cropped photo of a {}.",
    "the photo of a {}.",
    "a photo of one {}.",
    "a close-up photo of a {}.",
    "a bright photo of a {}.",
    "a dark photo of a {}.",
    "a clean photo of a {}.",
    "a dirty photo of a {}.",
    "a photo of a small {}.",
    "a photo of a large {}."
]

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("RN50", device=device)

# Build embeddings
all_embeddings = []
with torch.no_grad():
    for cname in class_names:
        prompts = [template.format(cname.replace('_', ' ')) for template in templates]
        tokenized = clip.tokenize(prompts).to(device)
        text_features = model.encode_text(tokenized)
        text_features /= text_features.norm(dim=-1, keepdim=True)
        class_embed = text_features.mean(dim=0)
        class_embed /= class_embed.norm()
        all_embeddings.append(class_embed.cpu().numpy())
print(all_embeddings)
# Save as .npy
np.save("clip_embed/sunrgbd_clip_a+cname_rn50_manyprompt_46c_coda.npy", np.stack(all_embeddings))
```

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/2d6b5d3e-6fea-4d4b-8375-fb03b7b76ebf" />
